# Generated by Django 3.1.2 on 2021-06-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('NEW', 'Создан'), ('IN_PROGRESS', 'Обработка'), ('DONE', 'Завершён')], default='NEW', verbose_name='статус')),
                ('total', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='товар')),
                ('description', models.TextField(default='', max_length=10000, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='заголовок')),
                ('text', models.TextField(default='', max_length=10000, verbose_name='текст подборки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_items', models.ManyToManyField(to='api.Product')),
            ],
            options={
                'verbose_name_plural': 'Product collections',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='количество')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.order', verbose_name='заказ')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='товар')),
            ],
            options={
                'verbose_name_plural': 'Positions',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(through='api.Position', to='api.Product'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=10000, verbose_name='текст отзыва')),
                ('stars', models.IntegerField(verbose_name='оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviwes', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='товар')),
            ],
            options={
                'verbose_name_plural': 'Product reviews',
                'unique_together': {('creator', 'product_id')},
            },
        ),
    ]
