# Generated by Django 3.1.2 on 2021-06-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
